name: CI-CD Pipeline for DEV

on:
  push:
    branches: [ "master"]

permissions:
    id-token: write
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        # with:
        #   # Disabling shallow clones is recommended for improving the relevancy of reporting
        #   fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        # with:
        #   projectBaseDir: .
        #   args: >
        #     -Dsonar.organization=Tunji-Amuzat
        #     -Dsonar.projectKey=django-realworld-example-app
        env:
          SONAR_TOKEN: 4d7e0afddbb833917b0d468cd0004fd6fe1534ba # ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io # ${{ vars.SONAR_HOST_URL }}
