name: CI-CD Pipeline for DEV

on:
  push:
    branches: [ "master"]

permissions:
    id-token: write
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        # with:
        #   # Disabling shallow clones is recommended for improving the relevancy of reporting
        #   fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1
        env:
          SONAR_TOKEN: sqa_f262817d92b27b436889858944c6615f8b2d13a3 # ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: 54.247.41.196:9000 # ${{ vars.SONAR_HOST_URL }}
